### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by fourk-ty** [Spijkervet/SimCLR#10]
Hi there, thank you for sharing your implementation.

I wonder your torch version is 1.3-1.5 or old version such as 1.1?

**Comment by Spijkervet** [comment]
Hi!

I have tested it on version 1.4 and 1.5. Let me know if it also works on older versions!

**Comment by fourk-ty** [comment]
Hi, it seems not work in older version-I tried it on version 1.1 and failed.
