### ISSUE TITLE
train on Imagenet

### ISSUE THREAD

**Issue by beyondpzk** [Spijkervet/SimCLR#14]
Hello, Have you trained on Imagenet with batch-size 256?

I am doing this, I found the curve of traing loss is very slow and steady. like this:
![image](https://user-images.githubusercontent.com/35320670/88748627-1071c080-d184-11ea-90da-5262d4b55f14.png)

**Comment by Spijkervet** [comment]
Hi Beyondpzk,

I have not trained my implementation on ImageNet yet. Let me know what results you obtain, the loss curve looks alright and comparable to mine on both CIFAR-10 and STL-10, which can be seen on the [Tensorboard.dev page.](https://tensorboard.dev/experiment/A3laNdafRBes0oR45Y6LiA)

**Comment by beyondpzk** [comment]
okay, thanks, I am training on Imagenet, several days later, it will finish training,

**Comment by beyondpzk** [comment]
Now, I have the baseline's result of training on 100% Imagenet and also train linear-W only using 100% ImageNet, bug I just got 40.8% accuracy.

**Comment by beyondpzk** [comment]
And the final loss curve is 

![image](https://user-images.githubusercontent.com/35320670/89166645-eddd0e80-d5ac-11ea-99ff-aa472ff578c8.png)
