### ISSUE TITLE
Slightly different strength parameter in CIFAR-10 setting

### ISSUE THREAD

**Issue by nzw0301** [Spijkervet/SimCLR#16]
Hi, thank you for sharing SimCLRv1 code by using pytorch. This repo is really helpful.

I realised that [the strength parameter `s` of `ColorJitter`](https://github.com/Spijkervet/SimCLR/blob/f75dc28ce1cf707124e77e99e5a7e4b3e967c734/modules/transformations/simclr.py#L12
) is slightly different from the paper's setting.
Appendix B.9. `CIFAR-10` of SimCLRv1 paper says 

> color distortion (strength=0.5),

So, we need to set `s=0.5` for CIFAR-10 experiments if we obtain the experimental results more accurately.

Best regards,

**Comment by gauenk** [comment]
you are correct. the value should be 0.5 according to the paper
