### ISSUE TITLE
What is world_size in this case? NT_Xent seems to ask this as a default argument but it hasn't been provided in the code?

### ISSUE THREAD

**Issue by ajaykrishnan23** [Spijkervet/SimCLR#22]

**Comment by hakanyi** [comment]
see https://github.com/Spijkervet/SimCLR/blob/654f05f107ce17c0a9db385f298a2dc6f8b3b870/main.py#L169
Hope that helps!

**Comment by AkihiroSasabe** [comment]
@Spijkervet 
I ran SimCLR in your Google Colab Notebook [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1ObAYvVKQjMG5nd2wIno7j2y_X91E9IrX) and got the same error at the 9th code cell.
So it should be better to modify the cell as follows.

**Before**
```python
criterion = NT_Xent(args.batch_size, args.temperature, args.device)
```
&darr;

**After**
```python
args.world_size = args.gpus * args.nodes 
criterion = NT_Xent(args.batch_size, args.temperature, args.device, args.world_size)
```
