### ISSUE TITLE
How to train a model in the same terminal when I used DDP training？

### ISSUE THREAD

**Issue by zs963048949** [Spijkervet/SimCLR#23]
I need to open 8 terminals when I used DDP training.It is so troubling.What method can I use in one terminal？

**Comment by smn57** [comment]
Use [`tmux`](https://github.com/tmux/tmux/wiki) to open more sessions in one terminal.

**Comment by steermomo** [comment]
You can use the command like this
```bash
python3 -m torch.distributed.launch --nproc_per_node 4 --master_port=9495 xxx.py
```


This command will start a DDP without using 8 terminals

**Comment by Spijkervet** [comment]
You can use `tmux` to do so.
