### ISSUE TITLE
normalize is not used in data augmentation

### ISSUE THREAD

**Issue by steermomo** [Spijkervet/SimCLR#25]
From the code, data augmentation used here is 
```python
torchvision.transforms.RandomResizedCrop(size=size),
torchvision.transforms.RandomHorizontalFlip(),  # with 0.5 probability
torchvision.transforms.RandomApply([color_jitter], p=0.8),
torchvision.transforms.RandomGrayscale(p=0.2),
torchvision.transforms.ToTensor(),
```

I think the data needs to be normalized here

**Comment by Spijkervet** [comment]
Hi steermomo!

I believe the original implementation also does not use data standardisation. Since the data is augmented randomly and at arbitrary scale during training, you would have to compile the dataset first to calculate its statistics and then start training.
