### ISSUE TITLE
I got some problems when I was testing

### ISSUE THREAD

**Issue by dmndxld** [Spijkervet/SimCLR#28]
I was running the code on google colab. Using your ResNet50 (256, 100) pre-trained models, run the linear_evaluation.py. I also set the model_path, epoch_num=100 and "resnet50" in config.yaml. 
Here is the error sign.
Files already downloaded and verified
Traceback (most recent call last):
  File "linear_evaluation.py", line 170, in <module>
    simclr_model = SimCLR(args, encoder, n_features)
  File "/content/drive/MyDrive/Test/simclr/simclr.py", line 26, in __init__
    nn.Linear(self.n_features, projection_dim, bias=False),
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 78, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (ResNet, int), but expected one of:
 * (*, torch.device device)
      didn't match because some of the arguments have invalid types: (ResNet, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)
 Could you help me to solve it? Many thanks.

**Comment by robbiejones96** [comment]
I ran into this too just now. I opened PR #29 to address this, but in the meantime it's a simple fix. Just change line 170 in `linear_evaluation.py` from

```
simclr_model = SimCLR(args, encoder, n_features)
```

to

```
simclr_model = SimCLR(encoder, args.projection_dim, n_features)
```

and you should be able to make it all the way through the starter command. Hope that helps, and thanks for posting this issue so I knew it wasn't just me who was having this problem :)

**Comment by dmndxld** [comment]
> I ran into this too just now. I opened PR #29 to address this, but in the meantime it's a simple fix. Just change line 170 in `linear_evaluation.py` from
> 
> ```
> simclr_model = SimCLR(args, encoder, n_features)
> ```
> 
> to
> 
> ```
> simclr_model = SimCLR(encoder, args.projection_dim, n_features)
> ```
> 
> and you should be able to make it all the way through the starter command. Hope that helps, and thanks for posting this issue so I knew it wasn't just me who was having this problem :)

THANK YOU! Now it works. 👍
