### ISSUE TITLE
Hello, If I want to use vgg16, how can I modify it?

### ISSUE THREAD

**Issue by dmndxld** [Spijkervet/SimCLR#31]
I get vgg16 by this
`import torchvision`
`def get_vgg(name, pretrained=False):`
 `   vggs = {`
  `      "vgg16": torchvision.models.vgg16(pretrained=pretrained),`
   ` }`
    `if name not in vggs.keys():`
        `raise KeyError(f"{name} is not a valid ResNet version")`
    `return vggs[name]`
and modify this
`encoder = get_vgg(args.vgg, pretrained=False)`
`n_features = encoder.classifier._modules['6'].in_features`
But it doen't work. Could u help me?

**Comment by Pattaro** [comment]
did you solve it? can u help me??
