### ISSUE TITLE
About the Cifar-10 accuracy

### ISSUE THREAD

**Issue by jimmy-dq** [Spijkervet/SimCLR#4]
Hi Spijkervet,
Thanks for your great implementation. In your project, I find that the accuracy on Cifar-10 is significantly lower than the result reported in the original paper (55% VS 90%+). Is it because that you use the projection_dim of 64 instead of 128 or small batch-size?

**Comment by Spijkervet** [comment]
That's a good question, I will have to take a deeper look into this. I believe in Figure B.5, they show an accuracy of ~84% on CIFAR-10 with ResNet-50. I can see if I can reproduce this.

**Comment by Spijkervet** [comment]
I believe I reproduced their accuracy on CIFAR10 in the latest commit, thanks!

[FINAL]  Loss: 0.46645689927614653       Accuracy: 0.8333333333333334

**Comment by jimmy-dq** [comment]
> I believe I reproduced their accuracy on CIFAR10 in the latest commit, thanks!
> 
> [FINAL] Loss: 0.46645689927614653 Accuracy: 0.8333333333333334

Wow, that's cool. Thanks.
