### ISSUE TITLE
Issue loading mask_correlated_samples

### ISSUE THREAD

**Issue by Kabongosalomon** [Spijkervet/SimCLR#7]
Hello, it's me again :), I'm having issue with this line as well 

`from utils import mask_correlated_samples, post_config_hook`

if I comment `mask_correlated_samples`, the line works perfectly and I can't see the `mask_correlated_samples` class in the utils file.

**Comment by Spijkervet** [comment]
Thanks for the heads-up, I adjusted the notebook! :)
