### ISSUE TITLE
Mismatching resnet50 model for CIFAR-10 experiments

### ISSUE THREAD

**Issue by alegonz** [Spijkervet/SimCLR#8]
Hi there, thank you for this amazing implementation :)

I've been trying to roll out my own implementation too for the CIFAR-10 experiments, and I noticed that you use the `resnet50` as implemented in torchvision and this differs from the one used in the paper in three ways:

1. The first convolution must be with a kernel 3x3 and a stride of 1.
2. No max pooling at the beginning.
3. torchvision's version of resnet is v1.5 which does the downsampling at the 3x3 convolution in the bottleneck blocks, as opposed to v1 which does it at the first 1x1 convolution.

While the 3rd difference [might not be that significant](https://github.com/pytorch/vision/issues/191#issuecomment-345694581), I think the first two could be significant given the tiny size of the CIFAR images. The details are in the Setup section at the beginning of page 17 in the paper.

Also, it seems that you also need to set the color jitter strength to 0.5 when training on CIFAR.

I made a short function that hacks torchvision's `resnet50` to match the one used in the paper and I can submit a PR if you like :)

**Comment by Spijkervet** [comment]
Hi! Thank you for taking a critical look at the implementation! Feel free to submit the PR, thanks!
